### Starting with a Numpy

In [3]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
#list of lists
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
type(b)

numpy.ndarray

In [7]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
b1 = np.zeros(2)
b1

array([0., 0.])

In [9]:
b2 = np.ones(3)
b2

array([1., 1., 1.])

In [10]:
b3 = np.empty(3)
b3

array([1., 1., 1.])

In [11]:
#with range of elements means array having range from to this limit
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [12]:
#with specific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [13]:
#Linear spaced arrays
h = np.linspace(0,10,num=5) #gives us 5 numbers whose difference is linear
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [16]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

## 2D array

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3D array

In [29]:
#Making And Reshaping a 3D Array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])