### Starting with a Numpy

In [1]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
#list of lists
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
type(b)

numpy.ndarray

In [5]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
b1 = np.zeros(2)
b1

array([0., 0.])

In [7]:
b2 = np.ones(3)
b2

array([1., 1., 1.])

In [8]:
b3 = np.empty(3)
b3

array([1., 1., 1.])

In [9]:
#with range of elements means array having range from to this limit
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [10]:
#with specific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [11]:
#Linear spaced arrays
h = np.linspace(0,10,num=5) #gives us 5 numbers whose difference is linear
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [13]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

## 2D array

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3D array

In [17]:
#Making and reshaping a 3D array
c =np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Creating an array using Numpy

In [18]:
# 1-D array
food= np.array(["Pakorray", "Samosa", "Raita"])
food

array(['Pakorray', 'Samosa', 'Raita'], dtype='<U8')

In [19]:
prices = np.array([5, 5, 5])
prices

array([5, 5, 5])

In [20]:
type(prices)

numpy.ndarray

In [21]:
len(food)

3

In [22]:
prices[2]

5

In [23]:
food[1]

'Samosa'

In [24]:
prices.mean()

5.0

In [25]:
#zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [26]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [28]:
#specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [29]:
# Specific intervals
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
#Line space
np.linspace(1, 100, num= 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [32]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [33]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array Functions

In [34]:
q = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
q

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [35]:
q.sort()
q

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [36]:
w= np.array([10.2,3.4,53.6,91.6,45.5])
w

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [37]:
e= np.concatenate((q,w))
e

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [38]:
e.sort()
e

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

## 2-D arrays

In [39]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [40]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [41]:
c = np.concatenate((a, b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [42]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [43]:
a= np.array([[5,6,7],
            [8,9,10],
            [10,11,12]])
a

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [44]:
a.ndim

2

In [45]:
# Size (number of elements)
a.size

9

In [46]:
#shape
a.shape

(3, 3)

In [47]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [48]:
# reshape (3*2=6 which is equal to given range)
b= a.reshape(3,2)
b   
 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
# Convert 1D into 2D
a = np.array([1,22,3,4,5,6,7,8,9])
a

array([ 1, 22,  3,  4,  5,  6,  7,  8,  9])

In [50]:
a.shape

(9,)

In [51]:
#Row wise 2D
b = a[np.newaxis, :]
b

array([[ 1, 22,  3,  4,  5,  6,  7,  8,  9]])

In [52]:
b.shape

(1, 9)

In [53]:
#Column Wise 2D
c = a[: , np.newaxis]
c

array([[ 1],
       [22],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [54]:
a

array([ 1, 22,  3,  4,  5,  6,  7,  8,  9])

In [55]:
a[2:9] # here print will be till 9 here inclusive bahaviour

array([3, 4, 5, 6, 7, 8, 9])

In [56]:
a*6

array([  6, 132,  18,  24,  30,  36,  42,  48,  54])

In [57]:
a+6

array([ 7, 28,  9, 10, 11, 12, 13, 14, 15])

In [58]:
a.sum()

65

In [59]:
a

array([ 1, 22,  3,  4,  5,  6,  7,  8,  9])

In [60]:
a.mean()

7.222222222222222